"""Core scientific state entities — domain-agnostic (§24.1).

The canonical path (SYS-001), in order:

    Artifact / SourceWork -> Claim / Observation -> Attestation -> RelationJudgment
      -> TransitionPolicy -> BeliefRevisionEvent -> EpistemicStateProjection

M0a implements the first four. The belief-event half arrives in M0b.

Nothing here may mention a physical quantity, a solver, or a default wavelength. If a field
would only make sense to a photonics researcher, it belongs in a DomainPack condition schema.
"""

from lab_brain.core.models.access import Actor, ArtifactOccurrence, ProjectMembership
from lab_brain.core.models.artifact import Artifact, RightsMetadata
from lab_brain.core.models.attestation import (
    FORBIDDEN_RELATION_FIELDS,
    Attestation,
    EvidenceField,
    ExtractionProvenance,
    Uncertainty,
)
from lab_brain.core.models.base import CoreModel, utc_now
from lab_brain.core.models.belief_event import (
    BELIEF_TERMINAL_STATES,
    BeliefRevisionEvent,
    BeliefState,
    BeliefTargetType,
)
from lab_brain.core.models.benchmark import BenchmarkPolicy, DisagreementMetric, MetricDirection
from lab_brain.core.models.capability import ActionType, Availability, Capability
from lab_brain.core.models.claim import Claim
from lab_brain.core.models.condition import (
    ConditionMatch,
    ConditionMismatch,
    ConditionSchemaError,
    ConditionSchemaRef,
    ConditionSchemaRegistration,
)
from lab_brain.core.models.cost import (
    CAPPED_DIMENSIONS,
    BudgetCaps,
    CostEntry,
    CostKind,
    CostVector,
    DependencyRisk,
)
from lab_brain.core.models.debate import (
    CritiqueReport,
    FalsifierChallenge,
    Objection,
    ObjectionKind,
    ObjectionSeverity,
    Position,
    ProposedPrediction,
    ResearchContract,
)
from lab_brain.core.models.enums import (
    FACTUAL_EPISTEMIC_TYPES,
    FAIL_CLOSED_SENSITIVITY,
    HIGH_WEIGHT_FIELD_STATUSES,
    IMPLEMENTED_INDEPENDENCE_BASES,
    ActorType,
    AuthorityComparison,
    ClaimIdentityStatus,
    ConditionMatchState,
    EpistemicType,
    EvidenceUnitType,
    ExtractionStatus,
    FieldStatus,
    IndependenceBasis,
    IndependenceRelation,
    LicenseClass,
    RelationType,
    RetrievalIndexKind,
    SecretScanStatus,
    SensitivityLabel,
    SourceOrigin,
    SourceWorkStatus,
    SourceWorkType,
    SubdivisionReason,
    TrustClass,
    VerificationStatus,
)
from lab_brain.core.models.evidence_bundle import (
    BUNDLE_SCHEMA_VERSION,
    IDENTITY_EXCLUDED_FIELDS,
    EvidenceBundle,
    ResearchIntent,
)
from lab_brain.core.models.evidence_unit import (
    EvidenceUnit,
    EvidenceUnitOccurrence,
    FigureContext,
    RetrievalCandidate,
    RetrievalRepresentation,
    SegmenterProvenance,
    SourceLocator,
    TableContext,
)
from lab_brain.core.models.execution_span import (
    SUBJECT_FIELD_FOR_TYPE,
    TERMINAL_SPAN_STATUSES,
    ExecutionSpan,
    SpanStatus,
    SpanType,
)
from lab_brain.core.models.failure import CandidateHeuristic, FailureAnalysis, ResolutionStatus
from lab_brain.core.models.governance_event import (
    GovernanceEvent,
    GovernanceEventType,
    GovernanceSubjectType,
    ResolutionEventKind,
)
from lab_brain.core.models.hypothesis import (
    FORBIDDEN_HYPOTHESIS_FIELDS,
    FORBIDDEN_STATUS_FIELDS,
    Hypothesis,
)
from lab_brain.core.models.hypothesis_set import HypothesisSet
from lab_brain.core.models.identifiers import (
    ContentHashError,
    artifact_id_for,
    compute_content_hash,
    compute_content_hash_from_path,
    compute_content_hash_from_stream,
    content_hash_for,
    evidence_unit_id_for,
    new_id,
    parse_content_hash,
    segmentation_witness_for,
)
from lab_brain.core.models.job import (
    ACTIVE_JOB_STATES,
    JOB_TRANSITIONS,
    TERMINAL_JOB_STATES,
    Job,
    JobState,
    JobTransitionError,
    Run,
    RunStatus,
)
from lab_brain.core.models.observation import Observation
from lab_brain.core.models.prediction import (
    PREDICTION_EFFECT_TYPES,
    OutcomeSpace,
    Prediction,
    PredictionAdmissionError,
    RelationJudgmentTemplate,
)
from lab_brain.core.models.prior_art import (
    DateRange,
    NoveltyAssessment,
    NoveltyScope,
    NoveltyStatus,
    PriorArtMatch,
    PriorArtOverlap,
    PriorArtSearchRecord,
    PriorArtSource,
)
from lab_brain.core.models.relation import (
    EPISTEMIC_RELATION_TYPES,
    IDENTITY_RELATION_TYPES,
    RelationJudgment,
)
from lab_brain.core.models.source_work import (
    RetractionCheck,
    SourceWork,
    WorkIdentifier,
)
from lab_brain.core.models.transition import (
    HypothesisView,
    IndependenceSummary,
    ReviewItemSpec,
    TransitionDecision,
    TransitionOutcome,
    TransitionPolicy,
    TransitionReason,
)
from lab_brain.core.models.validation import (
    ValidationFinding,
    ValidationReport,
    ValidationStatus,
)
from lab_brain.core.models.verification import (
    PlanDecision,
    PlanRationale,
    SelectionPolicy,
    SufficiencySummary,
    VerificationPlan,
)

__all__ = [
    "ACTIVE_JOB_STATES",
    "BELIEF_TERMINAL_STATES",
    "BUNDLE_SCHEMA_VERSION",
    "CAPPED_DIMENSIONS",
    "EPISTEMIC_RELATION_TYPES",
    "FACTUAL_EPISTEMIC_TYPES",
    "FAIL_CLOSED_SENSITIVITY",
    "FORBIDDEN_HYPOTHESIS_FIELDS",
    "FORBIDDEN_RELATION_FIELDS",
    "FORBIDDEN_STATUS_FIELDS",
    "HIGH_WEIGHT_FIELD_STATUSES",
    "IDENTITY_EXCLUDED_FIELDS",
    "IDENTITY_RELATION_TYPES",
    "IMPLEMENTED_INDEPENDENCE_BASES",
    "JOB_TRANSITIONS",
    "PREDICTION_EFFECT_TYPES",
    "SUBJECT_FIELD_FOR_TYPE",
    "TERMINAL_JOB_STATES",
    "TERMINAL_SPAN_STATUSES",
    "ActionType",
    "Actor",
    "ActorType",
    "Artifact",
    "ArtifactOccurrence",
    "Attestation",
    "AuthorityComparison",
    "Availability",
    "BeliefRevisionEvent",
    "BeliefState",
    "BeliefTargetType",
    "BenchmarkPolicy",
    "BudgetCaps",
    "CandidateHeuristic",
    "Capability",
    "Claim",
    "ClaimIdentityStatus",
    "ConditionMatch",
    "ConditionMatchState",
    "ConditionMismatch",
    "ConditionSchemaError",
    "ConditionSchemaRef",
    "ConditionSchemaRegistration",
    "ContentHashError",
    "CoreModel",
    "CostEntry",
    "CostKind",
    "CostVector",
    "CritiqueReport",
    "DateRange",
    "DependencyRisk",
    "DisagreementMetric",
    "EpistemicType",
    "EvidenceBundle",
    "EvidenceField",
    "EvidenceUnit",
    "EvidenceUnitOccurrence",
    "EvidenceUnitType",
    "ExecutionSpan",
    "ExtractionProvenance",
    "ExtractionStatus",
    "FailureAnalysis",
    "FalsifierChallenge",
    "FieldStatus",
    "FigureContext",
    "GovernanceEvent",
    "GovernanceEventType",
    "GovernanceSubjectType",
    "Hypothesis",
    "HypothesisSet",
    "HypothesisView",
    "IndependenceBasis",
    "IndependenceRelation",
    "IndependenceSummary",
    "Job",
    "JobState",
    "JobTransitionError",
    "LicenseClass",
    "MetricDirection",
    "NoveltyAssessment",
    "NoveltyScope",
    "NoveltyStatus",
    "Objection",
    "ObjectionKind",
    "ObjectionSeverity",
    "Observation",
    "OutcomeSpace",
    "PlanDecision",
    "PlanRationale",
    "Position",
    "Prediction",
    "PredictionAdmissionError",
    "PriorArtMatch",
    "PriorArtOverlap",
    "PriorArtSearchRecord",
    "PriorArtSource",
    "ProjectMembership",
    "ProposedPrediction",
    "RelationJudgment",
    "RelationJudgmentTemplate",
    "RelationType",
    "ResearchContract",
    "ResearchIntent",
    "ResolutionEventKind",
    "ResolutionStatus",
    "RetractionCheck",
    "RetrievalCandidate",
    "RetrievalIndexKind",
    "RetrievalRepresentation",
    "ReviewItemSpec",
    "RightsMetadata",
    "Run",
    "RunStatus",
    "SecretScanStatus",
    "SegmenterProvenance",
    "SelectionPolicy",
    "SensitivityLabel",
    "SourceLocator",
    "SourceOrigin",
    "SourceWork",
    "SourceWorkStatus",
    "SourceWorkType",
    "SpanStatus",
    "SpanType",
    "SubdivisionReason",
    "SufficiencySummary",
    "TableContext",
    "TransitionDecision",
    "TransitionOutcome",
    "TransitionPolicy",
    "TransitionReason",
    "TrustClass",
    "Uncertainty",
    "ValidationFinding",
    "ValidationReport",
    "ValidationStatus",
    "VerificationPlan",
    "VerificationStatus",
    "WorkIdentifier",
    "artifact_id_for",
    "compute_content_hash",
    "compute_content_hash_from_path",
    "compute_content_hash_from_stream",
    "content_hash_for",
    "evidence_unit_id_for",
    "new_id",
    "parse_content_hash",
    "segmentation_witness_for",
    "utc_now",
]
