"""Regenerate the Requirement Status table in IMPLEMENTATION_STATUS.md.

AGT-003 requires IMPLEMENTATION_STATUS.md to agree with the actual implementation state.
A hand-maintained 52-row table does not stay in agreement with anything, so the table is
derived from data that cannot lie about itself:

    milestone allocation   docs/milestones.yaml
    test evidence          @pytest.mark.requirement / @pytest.mark.spec_test in tests/
    spec test IDs          the §26 matrix

Status derivation:
    DEFERRED     milestone status is DEFERRED
    DONE         milestone status is DONE and a marked test exists
    IN_PROGRESS  milestone is IN_PROGRESS and a marked test exists
    BLOCKED      milestone is DONE but no marked test exists -- an inconsistency that
                 T-SPEC-002 also fails on, surfaced here rather than hidden
    TODO         otherwise

Usage:
    python scripts/update_status.py          # rewrite the table
    python scripts/update_status.py --check  # exit 1 if the file is stale (for CI)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from lab_brain.spec import (
    collect_marked_tests,
    load_milestones,
    load_spec,
    repo_root,
)

BEGIN = "<!-- BEGIN GENERATED: requirement-status -->"
END = "<!-- END GENERATED: requirement-status -->"


def build_table() -> str:
    spec = load_spec()
    catalog = load_milestones()

    evidence: dict[str, list[str]] = {}
    for test in collect_marked_tests():
        for requirement_id in test.requirement_ids:
            evidence.setdefault(requirement_id, []).append(test.module)

    lines = [
        BEGIN,
        "",
        "Generated by `scripts/update_status.py` from `docs/milestones.yaml` and test "
        f"markers. {len(spec.requirements)} requirements / {len(spec.test_ids)} tests.",
        "",
        "| ID | Milestone | Status | Spec Test | Test files |",
        "|---|---|---|---|---|",
    ]

    for milestone in catalog.milestones:
        for requirement_id in milestone.requirements:
            modules = sorted(set(evidence.get(requirement_id, [])))
            has_test = bool(modules)
            if milestone.status == "DEFERRED":
                status = "DEFERRED"
            elif milestone.status == "DONE":
                status = "DONE" if has_test else "BLOCKED"
            elif milestone.status == "IN_PROGRESS" and has_test:
                status = "IN_PROGRESS"
            else:
                status = "TODO"
            test_ids = ", ".join(f"`{t}`" for t in spec.tests_for(requirement_id))
            files = ", ".join(f"`{m}`" for m in modules) or "—"
            lines.append(
                f"| {requirement_id} | {milestone.milestone_id} | {status} | {test_ids} | {files} |"
            )

    counts: dict[str, int] = {}
    for line in lines:
        for status in ("DEFERRED", "BLOCKED", "IN_PROGRESS", "DONE", "TODO"):
            if f"| {status} |" in line:
                counts[status] = counts.get(status, 0) + 1
                break
    summary = " · ".join(f"{status} {counts[status]}" for status in sorted(counts))
    lines.extend(["", f"**Totals**: {summary}", "", END])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if the table is out of date")
    args = parser.parse_args()

    status_file = repo_root() / "IMPLEMENTATION_STATUS.md"
    original = status_file.read_text(encoding="utf-8")
    if BEGIN not in original or END not in original:
        print(f"error: {status_file.name} is missing the generated-table markers")
        return 2

    head, _, rest = original.partition(BEGIN)
    _, _, tail = rest.partition(END)
    updated = f"{head}{build_table()}{tail}"

    if updated == original:
        print("IMPLEMENTATION_STATUS.md is up to date")
        return 0
    if args.check:
        print("error: IMPLEMENTATION_STATUS.md is stale; run scripts/update_status.py")
        return 1
    status_file.write_text(updated, encoding="utf-8")
    print("IMPLEMENTATION_STATUS.md requirement table regenerated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
