"""The versioned message catalog (UX-006, §17.24).

WHAT THE RULE ACTUALLY FORBIDS.

    User-facing text MUST come from a versioned MessageCatalog keyed by reason_code.
    It MUST NOT be generated by an LLM at render time. An LLM-written failure explanation is an
    ungrounded inference presented as system fact, which contradicts P3 / EVI-003.

The second sentence is the reason and it is not a UI concern. A model asked "explain this error to
the user" produces a fluent, plausible account of a system it cannot observe -- and the user reads
it as what the system did. That is an INFERRED claim rendered as OBSERVED, which is the exact
failure EVI-003 exists to prevent, arriving through the one door nobody guards.

So rendering is a lookup. There is no model call anywhere in this module, and
`test_no_render_path_can_reach_a_model_slot` asserts that structurally rather than by convention.

WHY UNKNOWN CODES FAIL CLOSED TO A GENERIC ENTRY. §26's T-UX-006 row requires it: "an unknown
reason_code fails closed to a generic catalog entry". The alternative -- raising -- would turn a
missing catalog row into a second failure on top of the one being reported, and the user would
see a stack trace instead of the original problem. Returning the code itself as prose would leak
an internal identifier into a user surface. A generic entry says "something went wrong, here is
the reference" and keeps the error_id, which is the one thing support needs.

REUSING CODES RATHER THAN INVENTING SYNONYMS. The admission gate already emits seventeen
machine-readable `RefusalReason` values and the ingestion pipeline emits stage reason codes.
Those ARE reason codes; a parallel vocabulary would mean two names for one condition and two
catalog rows that drift. `catalog_for_refusal` maps the existing enum in, and a test asserts
every member resolves.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum


class Severity(StrEnum):
    """§17.24's `severity`.

    ``WARNING`` exists because §17.23 is explicit that EXTRACTION_WARNING "MUST NOT be rendered
    with failure styling. It is the UNKNOWN discipline working correctly (EVI-002). Rendering it
    as an error trains users to click ACCEPT to clear it, which silently reintroduces
    hallucinated completion."
    """

    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    BLOCKED = "BLOCKED"


@dataclass(frozen=True)
class CatalogEntry:
    """§17.24's entry shape, exactly."""

    reason_code: str
    user_summary: str
    user_cause: str
    user_next_steps: tuple[str, ...]
    severity: Severity


#: The code returned when a lookup misses. Named rather than inlined so the fail-closed path is
#: greppable and a test can assert on it without repeating a string.
GENERIC_REASON_CODE = "UNCLASSIFIED_FAILURE"


class MessageCatalog:
    """A versioned, locale-scoped catalog. Lookups only -- no generation, ever.

    Immutable after construction: a catalog that could be edited at runtime is not versioned in
    any useful sense, because two processes could render the same `reason_code` differently while
    both reporting the same `version`.
    """

    def __init__(
        self,
        catalog_id: str,
        locale: str,
        version: str,
        entries: tuple[CatalogEntry, ...],
    ) -> None:
        self.catalog_id = catalog_id
        self.locale = locale
        self.version = version
        self._entries: dict[str, CatalogEntry] = {}
        for entry in entries:
            if entry.reason_code in self._entries:
                raise ValueError(
                    f"catalog {catalog_id}@{version} declares {entry.reason_code} twice; two rows "
                    "for one code means the rendered text depends on iteration order"
                )
            self._entries[entry.reason_code] = entry
        if GENERIC_REASON_CODE not in self._entries:
            raise ValueError(
                f"catalog {catalog_id}@{version} has no {GENERIC_REASON_CODE} entry. UX-006 "
                "requires an unknown code to fail closed to a generic entry, and a catalog "
                "without one has nothing to fail closed *to*"
            )

    @property
    def codes(self) -> frozenset[str]:
        return frozenset(self._entries)

    def resolve(self, reason_code: str) -> CatalogEntry:
        """The entry for ``reason_code``, or the generic one.

        Never raises and never invents. An unknown code is an operational gap -- somebody emitted
        a code nobody wrote a row for -- and the user should still learn that something failed and
        get a reference they can quote.
        """
        entry = self._entries.get(reason_code)
        if entry is not None:
            return entry
        return self._entries[GENERIC_REASON_CODE]

    def knows(self, reason_code: str) -> bool:
        """Whether the code has a real row. Used by the conformance test, not by rendering."""
        return reason_code in self._entries


def _entry(
    code: str,
    summary: str,
    cause: str,
    steps: tuple[str, ...],
    severity: Severity = Severity.ERROR,
) -> CatalogEntry:
    return CatalogEntry(
        reason_code=code,
        user_summary=summary,
        user_cause=cause,
        user_next_steps=steps,
        severity=severity,
    )


#: The shipped English catalog.
#:
#: Every entry is written for a researcher, not an operator: no table names, no exception
#: classes, no file paths. §17.24 puts technical detail behind `technical_detail_ref` and an ACL
#: scope precisely so this text can be safe to show anyone with project access.
DEFAULT_ENTRIES: tuple[CatalogEntry, ...] = (
    _entry(
        GENERIC_REASON_CODE,
        "This item could not be processed.",
        "The system reported a problem it does not have a specific description for.",
        ("Quote the reference id when asking for help.",),
    ),
    # SEC-003 / ingestion
    _entry(
        "SEC003_SUSPECTED_CREDENTIAL",
        "This file was quarantined because it appears to contain a credential.",
        "A secret scan ran before the file was stored and found something that looks like a key "
        "or password.",
        (
            "Remove the credential and upload the file again.",
            "If this is a false positive, ask a project administrator to review it.",
        ),
        Severity.BLOCKED,
    ),
    _entry(
        "UX004_ALREADY_DURABLE",
        "This stage was skipped because the file was already stored.",
        "A retry resumed from the stage that failed, so scanning and storage did not run again.",
        (),
        Severity.INFO,
    ),
    _entry(
        "PARSE_TEXT_FAILED",
        "Some text could not be extracted from this document.",
        "The document was stored successfully, but the text extraction step did not finish.",
        (
            "Retry the extraction.",
            "If the document is a scan, try again with OCR.",
        ),
        Severity.WARNING,
    ),
    _entry(
        "OPS004_DB_COMMIT_FAILED",
        "This upload could not be recorded and left nothing behind.",
        "The file was staged but the database could not record it, so the staged copy was "
        "discarded.",
        ("Upload the file again.",),
    ),
    _entry(
        "SEGMENT_FAILED",
        "The document was stored but could not be divided into citable passages.",
        "Text extraction succeeded and the step that identifies quotable passages did not finish.",
        ("Retry the extraction.",),
        Severity.WARNING,
    ),
    _entry(
        "OPS004_PROMOTE_FAILED_COMPENSATED",
        "This upload was rolled back and left no partial record.",
        "The file store and the database could not be updated together, so the partial write was "
        "undone.",
        ("Upload the file again.",),
    ),
    # EVI-002 / EVI-003 / EVI-009 / EVI-010 admission
    _entry(
        "INFERENCE_TYPED_AS_FACT",
        "An AI-generated interpretation cannot be recorded as a measurement.",
        "The record was produced by a model but was submitted as observed, simulated or measured "
        "evidence.",
        ("Record it as an inference, or attach the measurement it is based on.",),
        Severity.BLOCKED,
    ),
    _entry(
        "INFERENCE_PROVENANCE_MISSING",
        "This AI-generated record is missing its provenance.",
        "Model outputs must record which model, prompt and evidence produced them.",
        ("Re-run the step so provenance is captured.",),
        Severity.BLOCKED,
    ),
    _entry(
        "INFERENCE_FLAG_CONTRADICTS_PROVENANCE",
        "This record's own provenance says it came from a model.",
        "The submission declared the record was not model-derived, and the stored provenance "
        "disagrees.",
        ("Submit it as an inference.",),
        Severity.BLOCKED,
    ),
    _entry(
        "REFERENCE_MISSING",
        "A measurement needs to say where it came from.",
        "Measured and simulated records must reference the run or file that produced them.",
        ("Attach the run or the source file and submit again.",),
    ),
    _entry(
        "REFERENCED_ARTIFACT_NOT_FOUND",
        "The file this record points at could not be found.",
        "The reference does not resolve to anything stored.",
        ("Check the reference, or upload the source file first.",),
    ),
    _entry(
        "REFERENCED_RUN_NOT_FOUND",
        "The run this record points at could not be found.",
        "No execution with that reference has been recorded.",
        ("Check the run reference, or re-run the analysis.",),
    ),
    _entry(
        "RUN_PRODUCED_NO_ARTIFACT",
        "The run this record points at produced no output.",
        "The execution either failed or finished without producing a file, so it cannot support "
        "a measurement.",
        ("Re-run the analysis and attach the successful run.",),
    ),
    _entry(
        "RUN_ARTIFACT_NOT_FOUND",
        "The run's output files could not be found.",
        "The run records output files, but none of them resolves to anything stored.",
        ("Re-run the analysis so its outputs are stored.",),
    ),
    _entry(
        "RUN_ARTIFACT_NOT_IN_PROJECT",
        "The run's output files are not available in this project.",
        "The files exist, but this project does not hold a copy of them.",
        ("Ask a project administrator to bring the files into this project.",),
        Severity.BLOCKED,
    ),
    _entry(
        "CROSS_PROJECT_RUN",
        "That run belongs to a different project.",
        "Evidence may only cite executions recorded in the same project.",
        ("Use a run from this project.",),
        Severity.BLOCKED,
    ),
    _entry(
        "BACKFILL_REFUSED",
        "This record has already been accepted and cannot be resubmitted with a new reference.",
        "Provenance is recorded when a record is admitted, not added afterwards.",
        ("Submit a new record instead of amending this one.",),
    ),
    _entry(
        "INVENTED_SCIENTIFIC_VALUE",
        "A value was supplied for a field the source does not report.",
        "Fields the source does not state must stay marked as unknown rather than being filled "
        "with a plausible value.",
        ("Leave the field unknown, or cite a source that reports it.",),
        Severity.BLOCKED,
    ),
    _entry(
        "BASELINE_UNIT_NOT_ADMISSIBLE",
        "This text came from a benchmark comparison and is not evidence.",
        "Fixed-length text fragments are produced only to measure retrieval quality.",
        ("Use the evidence unit from the document structure instead.",),
        Severity.BLOCKED,
    ),
    _entry(
        "EVIDENCE_UNIT_NOT_FOUND",
        "The evidence this record cites could not be found.",
        "The cited passage does not resolve to anything stored.",
        ("Re-ingest the source document.",),
    ),
    _entry(
        "EVIDENCE_BODY_NOT_CANONICAL",
        "The quoted text does not match the stored document.",
        "The text submitted differs from what the document actually says at that location.",
        ("Re-run retrieval so the quotation comes from the stored document.",),
        Severity.BLOCKED,
    ),
    _entry(
        "SEGMENTATION_NOT_VERIFIABLE",
        "The source document could not be re-read to verify this passage.",
        "The stored file could not be opened or parsed, so the passage could not be confirmed.",
        ("Try again later, or re-upload the document.",),
    ),
    _entry(
        "SEGMENTATION_NOT_REPRODUCIBLE",
        "This passage does not match what the document produces.",
        "Re-reading the source document does not yield this passage, so it may have been altered.",
        ("Re-ingest the document and cite the passage again.",),
        Severity.BLOCKED,
    ),
    _entry(
        "RECORDED_IMPLEMENTATION_UNAVAILABLE",
        "The version that produced this passage is no longer available.",
        "The passage records a parser or segmenter version this system cannot run.",
        ("Re-ingest the document with the current version.",),
    ),
    _entry(
        "EVIDENCE_LINK_NOT_DURABLE",
        "This record and the evidence it cites do not agree.",
        "The stored link between the record and its evidence is missing or points somewhere else.",
        ("Re-submit the record with the correct evidence reference.",),
        Severity.BLOCKED,
    ),
    _entry(
        "CROSS_PROJECT_UNIT",
        "That evidence belongs to a different project.",
        "Evidence may only be cited within the project that holds it.",
        ("Use evidence from this project.",),
        Severity.BLOCKED,
    ),
    _entry(
        "PROJECT_SCOPE_NOT_VERIFIABLE",
        "Project access for this evidence could not be checked.",
        "The system could not establish which project holds this evidence, so it refused rather "
        "than guessing.",
        ("Contact an administrator; this is a configuration problem.",),
        Severity.BLOCKED,
    ),
    _entry(
        "READ_NOT_PERMITTED",
        "You do not have access to the source of this record.",
        "The file behind this record is restricted.",
        ("Request access from a project administrator.",),
        Severity.BLOCKED,
    ),
    # UX-002 / retry and budget
    _entry(
        "BUDGET_EXHAUSTED",
        "This step was stopped because the project's budget is spent.",
        "The system is working normally; a spending limit stopped the work.",
        ("Ask an approver to raise the limit, or wait for the next budget period.",),
        Severity.BLOCKED,
    ),
    _entry(
        "BUDGET_GATE_UNAVAILABLE",
        "This step could not be retried automatically.",
        "Automatic retries spend project budget, and the budget check was not available.",
        ("Contact an administrator; this is a configuration problem.",),
        Severity.BLOCKED,
    ),
    _entry(
        "RETRY_LIMIT_REACHED",
        "This step failed after all its retries.",
        "The system retried automatically and the problem did not clear.",
        ("Retry manually, or report the reference id.",),
    ),
    _entry(
        "EXTERNAL_SERVICE_UNAVAILABLE",
        "An external service did not respond.",
        "A provider timed out, rate-limited the request, or was offline.",
        ("The system will retry automatically.",),
    ),
    _entry(
        "UNREADABLE_UPLOAD",
        "This file could not be read.",
        "The file appears corrupt, encrypted, or has no text layer.",
        ("Check the file opens on your machine and upload it again.",),
    ),
    # SEC-001 / SEC-004
    _entry(
        "EGRESS_BLOCKED_BY_POLICY",
        "This content may not be sent outside the approved boundary.",
        "The material is classified in a way that forbids external services.",
        ("Use a local model or tool for this step.",),
        Severity.BLOCKED,
    ),
    _entry(
        "EGRESS_CLEARANCE_MISSING",
        "You do not have clearance to send this content externally.",
        "External use of this material requires a clearance your account does not hold.",
        ("Request clearance from a project administrator.",),
        Severity.BLOCKED,
    ),
    _entry(
        "LICENSE_BLOCKS_CODE_GENERATION",
        "This source code may not be used for code generation.",
        "Its licence class is not permitted in generation context under this project's policy.",
        ("Ask a project administrator whether the policy can permit it.",),
        Severity.BLOCKED,
    ),
    _entry(
        "LICENSE_UNKNOWN",
        "This source code has no identified licence.",
        "Code with an unidentified licence is not used for generation unless a policy allows it.",
        ("Record the licence, or ask an administrator to permit unknown licences.",),
        Severity.BLOCKED,
    ),
    # UX-003
    _entry(
        "DIAGNOSTICS_SCOPE_REQUIRED",
        "You do not have permission to view technical details.",
        "Technical diagnostics require an additional access scope.",
        ("Request the diagnostics scope from a project administrator.",),
        Severity.BLOCKED,
    ),
    _entry(
        "ERROR_NOT_FOUND",
        "No such error reference in this project.",
        "The reference does not match anything you can see.",
        ("Check the reference id.",),
        Severity.INFO,
    ),
)


def default_catalog(locale: str = "en") -> MessageCatalog:
    """The shipped catalog. One version, incremented when entries change."""
    return MessageCatalog(
        catalog_id="lab_brain.messages",
        locale=locale,
        version="1.0.0",
        entries=DEFAULT_ENTRIES,
    )


@dataclass(frozen=True)
class RenderedMessage:
    """What a user surface shows. No technical detail, by construction.

    `technical_detail_ref` is a POINTER and is carried here deliberately: §17.24 requires the
    default payload not to inline technical detail, and a payload with no reference at all would
    leave a user unable to ask for it. Expanding it is `disclosure.py`'s decision.
    """

    reason_code: str
    summary: str
    cause: str
    next_steps: tuple[str, ...]
    severity: Severity
    catalog_version: str
    error_id: str | None = None
    technical_detail_ref: str | None = None
    #: True when the code had no row and the generic entry was substituted.
    fell_back: bool = False


def render(
    catalog: MessageCatalog,
    reason_code: str,
    *,
    error_id: str | None = None,
    technical_detail_ref: str | None = None,
) -> RenderedMessage:
    """Turn a reason code into user-facing text. A lookup, and only a lookup."""
    entry = catalog.resolve(reason_code)
    return RenderedMessage(
        reason_code=entry.reason_code,
        summary=entry.user_summary,
        cause=entry.user_cause,
        next_steps=entry.user_next_steps,
        severity=entry.severity,
        catalog_version=catalog.version,
        error_id=error_id,
        technical_detail_ref=technical_detail_ref,
        fell_back=not catalog.knows(reason_code),
    )


__all__ = [
    "DEFAULT_ENTRIES",
    "GENERIC_REASON_CODE",
    "CatalogEntry",
    "MessageCatalog",
    "RenderedMessage",
    "Severity",
    "default_catalog",
    "render",
]
